/**
 * Cloudflare Worker entry point (wrangler.jsonc "main").
 *
 * Requests are handled by the Next.js app as built by the OpenNext adapter
 * (`npm run cf:build` generates .open-next/worker.js). This file only adds the
 * scheduled handler that replaces vercel.json's daily cron: it drains the AI
 * queue through the existing /api/worker/drain route, authenticated with
 * AI_WORKER_SECRET. Without a usable secret the route answers 401 and nothing
 * happens.
 */
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import { default as handler } from '../.open-next/worker.js';

interface Env {
  AI_WORKER_SECRET?: string;
}

interface Handler {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response>;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

const app = handler as Handler;

export default {
  fetch: app.fetch,

  async scheduled(_controller: unknown, env: Env, ctx: ExecutionContext): Promise<void> {
    const request = new Request('https://talentiq.internal/api/worker/drain?limit=3&spacing=2000', {
      method: 'POST',
      headers: { authorization: `Bearer ${env.AI_WORKER_SECRET ?? ''}` },
    });
    ctx.waitUntil(
      app.fetch(request, env, ctx).then(async (res) => {
        console.log(`[cron] AI queue drain: HTTP ${res.status}`);
      }),
    );
  },
};
